### ISSUE TITLE
Error while loading DeepLabV3Plus-ResNet50 model from checkpoint with --separable_conv flag 

### ISSUE THREAD

**Issue by free-bit** [VainF/DeepLabV3Plus-Pytorch#39]
It seems that DeepLabV3Plus-ResNet50 model is not trained while --separable_conv flag is active because trying to load the weights when this flag is active, causes an error at the checkpoint loading stage.

Command:

`python main.py --model deeplabv3plus_resnet50 --separable_conv --ckpt checkpoints/best_deeplabv3plus_resnet50_voc_os16.pth --test_only --save_val_results`

Error:

> RuntimeError: Error(s) in loading state_dict for DeepLabV3:
> 	Missing key(s) in state_dict: "classifier.aspp.convs.1.0.body.0.weight", "classifier.aspp.convs.1.0.body.1.weight", "classifier.aspp.convs.2.0.body.0.weight", "classifier.aspp.convs.2.0.body.1.weight", "classifier.aspp.convs.3.0.body.0.weight", "classifier.aspp.convs.3.0.body.1.weight", "classifier.classifier.0.body.0.weight", "classifier.classifier.0.body.1.weight". 
> 	Unexpected key(s) in state_dict: "classifier.aspp.convs.1.0.weight", "classifier.aspp.convs.2.0.weight", "classifier.aspp.convs.3.0.weight", "classifier.classifier.0.weight".

Perhaps, if you are still keeping the commands that you used for training the models for which you shared the weights and publish those commands, it might be easier to use the pre-trained models.

I just wanted to note this point in case somebody else also experiences the same issue. Overall, the repo is really helpful. Thank you.

**Comment by VainF** [comment]
Hi @free-bit , thanks for your suggestions. The readme was updated.

**Comment by lcr9875** [comment]
@VainF  I encountered the opposite situation.I get weight by -separable_conv,Then I encountered problems during the test.

RuntimeError: Error(s) in loading state_dict for DeepLabV3:
Missing key(s) in state_dict: "classifier.aspp.convs.1.0.weight", "classifier.aspp.convs.2.0.weight", "classifier.aspp.convs.3.0.weight", "classifier.classifier.0.weight".
Unexpected key(s) in state_dict: "classifier.aspp.convs.1.0.body.0.weight", "classifier.aspp.convs.1.0.body.1.weight", "classifier.aspp.convs.2.0.body.0.weight", "classifier.aspp.convs.2.0.body.1.weight", "classifier.aspp.convs.3.0.body.0.weight", "classifier.aspp.convs.3.0.body.1.weight", "classifier.classifier.0.body.0.weight", "classifier.classifier.0.body.1.weight".

I think it's because the weight name was changed during training，How to modify the code to test after -separable_conv?

**Comment by VainF** [comment]
Hi @lcr9875, the pretrained weights are only compatible with defalt models that does not use seperable convs. You may train your own models from scratch if you want to enable seperate convs.

**Comment by lcr9875** [comment]
@VainF  Hi,I train it without pretrained weights by myself,but I get this problem while test the new weight.I read the code and i think  the extra "body.x" in the weight is caused by -separable, so how should I test the weight with "body.x"? Thank you very much.
