### ISSUE TITLE
IndexError: Target 225 is out of bounds.

### ISSUE THREAD

**Issue by IremYoldas** [VainF/DeepLabV3Plus-Pytorch#91]
I'm trying to train my own dataset with this repo. I covered my dataset to Pascal format and I changed num classes, cmap. As I searched in web this error happens because of index of classes. I can't find class ids. Please help me, I stucked in here. Thanks in advance.

**Comment by VainF** [comment]
Hi @IremYoldas, I guess 225 is the class ID for background pixels? If so, you can simply set the [ignore_index (Line 272)](https://github.com/VainF/DeepLabV3Plus-Pytorch/blob/f65c200148e75d0f979a1ca20becae8504a653fa/main.py#L272) to 225 to ignore it. But I think 255 seems more resonable than 225. Maybe it is caused by a typo in your data transformation?

**Comment by IremYoldas** [comment]
We are on the same page but I have no idea where 225 came from. I set the `ignore_index` to 225 and my problem seems like resolved.  Thank you so much for your help.
